version: "3"
services:
  test:
    build: .
    ports:
      - "5700:5700"
    container_name: adapter-earth-engine-test
    environment:
      DEBUG: "True"
      GATEWAY_URL: http://mymachine:9000
      LOCAL_URL: http://mymachine:5700
      MICROSERVICE_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      PORT: 5700
      EE_PRIVATE_KEY: ${EE_PRIVATE_KEY}
      EE_ACCOUNT: ${EE_ACCOUNT}
      AWS_REGION: "us-east-1"
      REQUIRE_API_KEY: "True"
      AWS_CLOUD_WATCH_LOGGING_ENABLED: "True"
    command: test
