version: "3"
services:
  test:
    build: .
    ports:
      - "5700:5700"
    container_name: adapter-earth-engine-test
    environment:
      DEBUG: "True"
      CT_REGISTER_MODE: "False"
      CT_URL: http://mymachine:9000
      API_VERSION: v1
      LOCAL_URL: http://mymachine:5700
      CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      PORT: 5700
    command: test
