version: "3"
services:
  develop:
    build: .
    ports:
      - "5700:5700"
    container_name: adapter-earth-engine-develop
    environment:
      PORT: 5700
      GATEWAY_URL: http://mymachine:9000
      LOCAL_URL: http://mymachine:5700
      MICROSERVICE_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      ENVIRONMENT: dev
      DEBUG: "True"
      EE_PRIVATE_KEY: ${EE_PRIVATE_KEY}
      EE_ACCOUNT: ${EE_ACCOUNT}
      API_VERSION: v1
      AWS_REGION: "us-east-1"
      REQUIRE_API_KEY: "True"
      AWS_SECRET_ACCESS_KEY: 34VLzL2E885g03QOp60KyL3pZn6kFlkmdkPeHfoE
      AWS_ACCESS_KEY_ID: AKIA4IKXSDIU3C3IVVQE
    command: develop
    volumes:
      - ./adapterearthengine:/opt/adapter-earth-engine/adapterearthengine
    restart: always
