develop:
  extends:
    file: base.yml
    service: base
  container_name: adapter-earth-engine-develop
  environment:
    CT_REGISTER_MODE: auto
    CT_URL: http://mymachine:9000
    LOCAL_URL: http://mymachine:5700
    CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
    ENVIRONMENT: dev
    DEBUG: "True"
    EE_PRIVATE_KEY: ${EE_PRIVATE_KEY}
    EE_ACCOUNT: ${EE_ACCOUNT}
    API_VERSION: v1
  command: develop
  volumes:
    - ./adapterearthengine:/opt/adapter-earth-engine/adapterearthengine
  restart: always
