apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: gee
  name: gee
spec:
  progressDeadlineSeconds: 2147483647
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      name: gee
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: gee
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - apps
      containers:
        - args:
            - start
          env:
            - name: PORT
              value: "5700"
            - name: ENVIRONMENT
              value: staging
            - name: LOCAL_URL
              value: http://gee.default.svc.cluster.local:5700
            - name: CT_URL
              valueFrom:
                secretKeyRef:
                  key: CT_URL
                  name: mssecrets
            - name: CT_TOKEN
              valueFrom:
                secretKeyRef:
                  key: CT_TOKEN
                  name: mssecrets
            - name: CT_REGISTER_MODE
              valueFrom:
                secretKeyRef:
                  key: CT_REGISTER_MODE
                  name: mssecrets
            - name: API_VERSION
              valueFrom:
                secretKeyRef:
                  key: API_VERSION
                  name: mssecrets
            - name: EE_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  key: EE_PRIVATE_KEY
                  name: mssecrets
            - name: EE_ACCOUNT
              valueFrom:
                secretKeyRef:
                  key: EE_ACCOUNT
                  name: mssecrets
          image: vizzuality/gee
          imagePullPolicy: Always
          name: gee
          ports:
            - containerPort: 5700
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 512M
            requests:
              cpu: 500m
              memory: 256M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30
